# fly.toml app configuration file generated for teofum-remix-jokes on 2023-05-15T02:48:23-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "teofum-remix-jokes"
primary_region = "eze"

[env]
  DATABASE_URL = "file:/data/sqlite.db"
  PORT = "8080"

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
